### PR TITLE
Adding Behat Functionality to Webstarter

### PR DESCRIPTION
**Pull request by generalconsensus**
These associated changes create an initial step for using Behat for new webstarter projects

### CODE REVIEW

**Comment by mortona42** [comment]
w00t!

**Comment by wwhurley** [comment]
I have a question about whether we should have some of those configuration files handled by the provisioner? That means they are harder to manage at the project level. Shouldn't stop us from moving forward with this, but do want to flag that as something we might want to come back to.

**Comment by generalconsensus** [comment]
@wwhurley I assume that we are talking about the behat.yml.erb, and the test features? If so can -- perhaps I can still push them up as stubs (suggestions for the project) which ultimately will be altered. Perhaps I can deploy them as behat.yml.suggested, test-js.feature.suggested, and test.feature.suggested. Does that make more sense?

**Comment by wwhurley** [comment]
I'm thinking that may be an area where we'd want to explore an add-on to the Yeoman generator. Moar Yeoman generators! :)

**Comment by wwhurley** [comment]
I ran into an issue on one test installation of the behat installation exec timing out. Probably need to increase the timeout period. See http://docs.puppetlabs.com/puppet/latest/reference/type.html#exec-attribute-timeout.

**Comment by generalconsensus** [comment]
@wwhurley Should I set default timeouts for all provision tasks or was there a specific one you had a problem with? I might look into doing it for the composer install action here: 

https://github.com/forumone/puppet-forumone/pull/23/files#diff-0e233e4f50508b627ede0878f43cf5f9R195

**Pull request merged**
